name: My First Yml flow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List the files
        run: |
          echo "Run multiple commands in a single runner"
          ls -R

      - name: Run bash file
        run: |
          chmod +x .github/workflows/script.sh
          ./.github/workflows/script.sh