name: Run bash file

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List the files
        run: |
          echo "Run multiple commands in a single runner"
          ls -R

      - name: Run bash file
        run: |
          sudo apt-get update && sudo apt-get install -y cowsay
            cowsay -f dragon "Run for cover, I am a Dorgan....RAWR" >>dragon.txt

  second_job:
    runs-on: ubuntu-latest
    needs: first_job

    steps:
      - name: View dragon file.
        run: cat dragon.txt