name: Set varibale and secrets

on:
    schedule:
      - cron: "*/1 * * * *"
      
#    push
    
jobs:
    docker-build:
        runs-on: ubuntu-latest
        steps:
          - name: Docker build
            run: 